version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      # upstream DNS should be the dns-crypt service only
      PIHOLE_DNS_: 'dnscrypt#5053'
      # Enter a secure password for accessing web portal, otherwise it will be random
      WEBPASSWORD: 'webadminpassword'
      TZ: 'America/New_York'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
  dnscrypt:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
    volumes:
      - '/etc/dnscrypt:/config'
    restart: unless-stopped
